@api = http://localhost:3000

### GET USER
GET {{api}}/usuario
Content-Type: application/json

### CREATE USER
POST {{api}}/usuario
Content-Type: application/json

{}

### UPDATE USER
PUT {{api}}/usuario/1
Content-Type: application/json

{}

### DELETE USER
DELETE {{api}}/usuario/1
Content-Type: application/json

### GET ALL NOTES
GET {{api}}/nota
Content-Type: application/json

### GET ONE NOTE
GET {{api}}/nota/1
Content-Type: application/json

### CREATE NOTE
POST {{api}}/nota
Content-Type: application/json

{}

### UPDATE NOTE
PUT {{api}}/nota/1
Content-Type: application/json

{}

### DELETE NOTE
DELETE {{api}}/nota/2
Content-Type: application/json